# ── Фронтенд: accelerator-sber.ru ────────────────────────────────────────────
server {
    listen 80;
    server_name accelerator-sber.ru www.accelerator-sber.ru;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        proxy_pass http://backend:8000/health;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
