services:
  db:
    image: postgres:16-alpine
    container_name: sberstart_db
    environment:
      POSTGRES_DB: sberstart
      POSTGRES_USER: sber
      POSTGRES_PASSWORD: sber_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sber -d sberstart"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sberstart_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://sber:sber_pass@db:5432/sberstart
      SECRET_KEY: sberstart_demo_secret_2024
      GIGACHAT_AUTH_KEY: NTQzYWQzZDgtN2IyYi00YjcxLWIwNTAtZTY3NDhkZTQ2OTgzOmY2NTkwNDk5LTQ3NDItNDZlYS05NmM0LWVlNDc4N2RhMDY4Mw==
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://api.accelerator-sber.ru/api/v1
    container_name: sberstart_frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx-proxy:
    image: nginx:alpine
    container_name: sberstart_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  pgdata:
